#!/bin/bash

# LICENSE
#
# "THE BEER-WARE LICENSE" (Revision 42):
# "Sven Strittmatter" <ich@weltraumschaf.de> wrote this file.
# As long as you retain this notice you can do whatever you want with
# this stuff. If we meet some day, and you think this stuff is worth it,
# you can buy me a beer in return.
#
# @author    Weltraumschaf
# @copyright Copyright (c) 01.12.2010, Sven Strittmatter.
# @version   0.2
# @license   http://www.weltraumschaf.de/the-beer-ware-license.txt

basedir=$(dirname $0)

phpunit $* --configuration $basedir/tests/phpunit.xml \
        --bootstrap $basedir/tests/bootstrap.php \
        --coverage-html $basedir/tests/coverage \
        --coverage-clover $basedir/tests/coverage/clover.xml \
        $basedir/tests/lib