@startuml

skinparam componentStyle uml2

node "Server" {
    [SSHd]
    [File Storage] as fs
    [Backup Storage] as bs

    package "Docker" {
        [MySQL]
        [Nginx]
        [Sonar]
        [Jenkins]
        [Git]

        Sonar .> MySQL
    }

    MySQL ..> fs
    Nginx ..> fs
    Nginx ..> Jenkins
    Nginx .> Sonar
    Nginx ..> Git
    Jenkins ..> fs
    Git ..> fs
}

node NAS #white
SSH ..> SSHd
NAS ..> bs
fs ..> NAS
HTTPS ..> Nginx
Git ..> SSHd

@enduml
